spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    master:
      driver-class-name: ${spring.datasource.driver-class-name}
      url: jdbc:mysql://10.0.0.123:3309/test?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
    slave:
      driver-class-name: ${spring.datasource.driver-class-name}
      url: jdbc:mysql://10.0.0.123:3308/test?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456