server:
  port: 6080

logging:
  level:
    io:
      kimmking:
        cache : info

# 作业，在这里使用spring boot配置各项内容，
spring:
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 32
        max-wait: 10ms
