DROP DATABASE IF EXISTS test;

CREATE DATABASE test;

USE test;

CREATE TABLE user (
  user_id BIGINT AUTO_INCREMENT NOT NULL,
  user_name VARCHAR(50) NOT NULL,
  PRIMARY KEY(user_id)
) Engine=INNODB DEFAULT CHARSET=UTF8;